In [32]:
import numpy as np
np.set_printoptions(suppress=True)

In [33]:
A = np.array([2,1,2,1,-2,1,1,2,3,1,1,1]).reshape((4,3))
b= np.array([6,1,5,2]).T


In [34]:
# 1(a)
#Normal Equation
# ATAx = ATb
x = np.linalg.solve(A.T@A, A.T@b)
print(x)

[1.7 0.6 0.7]


In [35]:
# 1(b)
r = A@x -b
print(r)

[-0.6  0.2 -0.   1. ]


In [39]:
# 1(c)
W = np.diag([1000,1,1,1])
x = np.linalg.solve(A.T@W@A, A.T@W@b)
r = r = A@x -b
print(r)

[2.17244031 0.69218347 0.48106425]
[-0.00080741  0.26913761 -0.          1.34568803]
