In [1]:
import numpy as np
np.set_printoptions(suppress=True)

In [2]:
A = np.array([2,1,2,1,-2,1,1,2,3,1,1,1]).reshape((4,3))
b= np.array([6,1,5,2]).T


In [3]:
# 1(a)
#Normal Equation
# ATAx = ATb
x = np.linalg.solve(A.T@A, A.T@b)
print(x)

[1.7 0.6 0.7]


In [4]:
# 1(b)
'''
The solution is unique beacuse the least-squares problem is a quadratic function,
which is strictly-convex, strictly-convex functions has a single global minimum.
'''
r = A@x -b
print(r)

[-0.6  0.2 -0.   1. ]


In [5]:
# 1(c)
W = np.diag([1000,1,1,1])
x = np.linalg.solve(A.T@W@A, A.T@W@b)
r = r = A@x -b
print(r)

[-0.00080741  0.26913761 -0.          1.34568803]


In [6]:
# 1(d)
_lambda = 0.1
x =np.linalg.solve(A.T@A + np.eye(3)*_lambda , A.T@b)
r = r = A@x -b
print(x)
print(r)

[1.61338023 0.58116926 0.7557214 ]
[-0.68062748  0.20676311  0.04288294  0.95027089]


In [7]:
# 2(a)
'''
if labmda is eigenvalue of C then there is a v for which:
    Cv = lambda*v
now:
    (C-I)v = Cv - Iv = lambda*v - v = (lambda-1)*v
'''

'\nif labmda is eigenvalue of C then there is a v for which:\n    Cv = lambda*v\nnow:\n    (C-I)v = Cv - Iv = lambda*v - v = (lambda-1)*v\n'

In [8]:
'''
full rank for matrix A mXn for m>n means that rank(A) = n
<--
if A.T@A is invertable, therefor the only solution to A.T@Ax=0 is x =0
therefor x.TA.T@Ax 
'''

'\nfull rank for matrix A mXn for m>n means that rank(A) = n\n<--\nif A.T@A is invertable, therefor the only solution to A.T@Ax=0 is x =0\ntherefor x.TA.T@Ax \n'

In [20]:
# 3c
A = np.array([5,6,7,8,1,3,5,4,1,0.5,4,2,3,4,3,1]).reshape((4,4))
B = np.array([0.57,0.56,0.8,1,1.5,4,6.7,4.9,0.2,0.1,1,0.6,11,30,26,10]).reshape((4,4))
D = np.zeros((4,4))
# (A[i].T @ A[i]) is a scalar, there for its inverse is just 1/(A[i].T @ A[i])
for i in range(4):
    D[i,i] = (A[i].T @ B[i]) / (A[i].T @ A[i])
print(D)

[[0.11385057 0.         0.         0.        ]
 [0.         1.30588235 0.         0.        ]
 [0.         0.         0.25647059 0.        ]
 [0.         0.         0.         6.88571429]]
